### ISSUE TITLE
Раздел документации Configuration

### ISSUE THREAD

**Issue by aaa4xu** [LaravelRUS/docs#162]
Данные раздел имеет пустой файл (и, соответственно, пустую страницу на сайте перевода) + в разделе "Статус перевода" стоит статус "перевод не требуется". Это баг или страница не нуждается в переводе?

**Comment by VladShcherbin** [comment]
[Ссылка](http://laravel.su/docs/5.4/configuration) на версию 5.4 теперь рабочая, сам раздел документации на сайте нуждается в обновлении, за прогрессом которого можно следить [здесь](https://github.com/LaravelRUS/laravel.ru).
