### ISSUE TITLE
Ошибка в документации.

### ISSUE THREAD

**Issue by iliyaZelenko** [LaravelRUS/docs#195]
У вас в разделе http://laravel.su/docs/5.2/blade и в других версиях вместо 

`@parent` написано `@`

конкретно в этом коде:

```
@section('sidebar')
    @

    <p>This is appended to the master sidebar.</p>
@endsection
```

[Как минимум 1 человека уже запутали](https://ru.stackoverflow.com/questions/886334/%D0%9D%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%B8%D0%B2%D0%B0/886423#886423).

**Comment by vladshcherbin** [comment]
хм, [в исходнике](https://github.com/laravel/docs/blob/5.2/blade.md) идёт `@@parent`.

я подумал, что это опечатка и заменил на `@parent`, после чего его перестало вообще показывать 🤦‍♂️ 

предположу, что это баг парсера на серваке, нужно тестить

добавил issue в репу сайта - https://github.com/LaravelRUS/laravel.ru/issues/88

**Comment by SerafimArts** [comment]
fixed
