### ISSUE TITLE
6 версия

### ISSUE THREAD

**Issue by IlyaVorozhbit** [LaravelRUS/docs#200]
Здравствуйте, планируете 6 версию переводить, или это не так важно, как мне кажется?

**Comment by slider23** [comment]
Можно попробовать. Надо будет посмотреть объём работы.

**Comment by IlyaVorozhbit** [comment]
@slider23 если нужно будет помочь, упомяните

**Comment by IlyaVorozhbit** [comment]
@slider23 не оценили?

**Comment by slider23** [comment]
@IlyaVorozhbit в принципе, оценил - http://laravel.su/status . Кажется, у нас накопилась некоторая неконсистентность в переводе, но я мне не удалось поймать, где именно. Наверное, можно начинать переводить 6.х , просто дополнительно хорошо бы сличать оригинал и перевод, нет ли явно пропущенных кусков, без фанатизма, но вдруг что бросится в глаза.

**Comment by IlyaVorozhbit** [comment]
@slider23 здорово, смогу начать в скором времени
