### ISSUE TITLE
Прогрорегресс

### ISSUE THREAD

**Issue by russsiq** [LaravelRUS/docs#219]
Куда же делась ваша команда:

> Перевод документации Laravel 8.x, выполненный командой https://rularavel.com

**Comment by russsiq** [comment]
https://github.com/LaravelRUS/docs/commit/eeb85075f54e782cedeff2062c99248e087fb66f#r50289019

**Comment by russsiq** [comment]
Пережеванные сообщества: что Хабр, что SO.  Раз такое появляется в общественном доступе, то пора задуматься об урлах и ендпоитах.

Какого божества был выбран фрагмент Rus, если все могло уложиться в транслитирации. Блювантина!

**Comment by slider23** [comment]
> Куда же делась ваша команда:
> 
> > Перевод документации Laravel 8.x, выполненный командой [rularavel.com](https://rularavel.com)

Я думал, это ваша команда. Мне первой попалась ссылка на их репу, я общался с человеком оттуда, думая, что он автор этого перевода. Он меня в этом не переубеждал. Затем оказалось, что это не так - я увидел вашу репу. Ссылку на них я убрал. Вы попросили ссылки на себя не давать, поэтому на вашу репу я её не поставил. Вы описали в issue, как делался перевод, я отметил это в баннере.

Спасибо ещё раз за труд по переводу, это реально большая работа и важно для новичков.

**Comment by russsiq** [comment]
Я попросил убрать ссылку, чтобы она не фигурировала на каждой странице, ради вашего блага.

Яндекс уже запустил сою талоку. Неужели так сложно убрать ссылку на опосредованных товарищей? Уберите к херам ссылку на этих товарищей.

**Comment by russsiq** [comment]
Какого хрена мой репо должен попадать в черный список яндекса? Как вам, сука, еще объяснить? Не имеют те гандоны отношения к переводу и точка.

**Comment by vladshcherbin** [comment]
Ссылку из репозитория убрал.

@Butochnikov , @slider23 , @SerafimArts добавьте человека выше в чс организации. Перевод переводом, но хамлу в сообществе не место.

**Comment by SerafimArts** [comment]
> @Butochnikov , @slider23 , @SerafimArts добавьте человека выше в чс организации. Перевод переводом, но хамлу в сообществе не место.

Да, сделал, уже несколько жалоб от разных людей на него. Очень жаль.
