### ISSUE TITLE
Предлагаю сохранение номеров строк

### ISSUE THREAD

**Issue by Sergey-Shabanov** [LaravelRUS/docs#223]
Сабж: Предлагаю сохранение номеров строк в переводах документации 8.х относительно оригинальных файлов документации.

На мой ~~скромный~~ взгляд, это позволит свободнее ориентироваться в файле и при реализации перевода сразу переходить к нужной строке, а не как сейчас, искать её через `Ctrl+f `

**Comment by slider23** [comment]
Но это же придётся перелопатить всю документацию, чтобы количество строк совпадало, если я правильно понимаю предложение.. Это огромный объём работы. Нажать Ctrl-F чтобы найти ближайший заголовок или кусок текста по-моему гораздо проще.

**Comment by Sergey-Shabanov** [comment]
> Но это же придётся перелопатить всю документацию, чтобы количество строк совпадало, если я правильно понимаю предложение.. Это огромный объём работы. Нажать Ctrl-F чтобы найти ближайший заголовок или кусок текста по-моему гораздо проще.

Если данное предложение вынести как рекомендацию в [правила перевода](https://laravel.su/articles/rus-documentation-contribution-guide), то в последующих переводах можно придерживаться данного правила, как самим, так и постараются соблюдать другие контрибюторы (но это не точно).
Попробуйте добавить как рекомендацию, это прям клёво!
