### ISSUE TITLE
Неправильно записан номер коммита

### ISSUE THREAD

**Issue by Sergey-Shabanov** [LaravelRUS/docs#224]
В файле https://github.com/LaravelRUS/docs/blame/8.x/installation.md#L1 требуется поправить номер коммита git 13f770acbfe97eaa2e77534144ab8d4513d04a04
Сейчас `egit 13f770acbfe97eaa2e77534144ab8d4513d04a04` с пробелами в начале

**Comment by slider23** [comment]
Да, действительно, спасибо, что заметил.
